coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: backend
      paths:
        - server/
      statuses:
        - type: project
          target: auto
          threshold: 0%
    - name: queue
      paths:
        - background/
        - queuelogic/
      statuses:
        - type: project
          target: auto
          threshold: 0%