# Build Stage
FROM python:3.11-alpine AS builder
WORKDIR /app
RUN pip install --no-cache-dir mkdocs mkdocs-material
COPY mkdocs.yml ./
COPY docs/ ./docs/
RUN mkdocs build

# Serve Stage
FROM nginx:alpine
COPY --from=builder /app/site /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
