apiVersion: batch/v1
kind: CronJob
metadata:
  name: gramophile-validator
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeName: klust1
          containers:
            - name: gramophile-validator
              image: registry.brotherlogic-backend.com/brotherlogic/gramophile-validator:0.1055.0 # {"$imagepolicy": "flux-system:gramophile-validator"}
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
