{
 "title": "Record Collection",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Last scrape",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gramophile_overseer_result*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (result)(gramophile_overseer_loop_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg by (folder)(gramophile_overseer_collection{folder!=\"1613206\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2024 Sales",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "gramophile_overseer_sales{year=\"2024\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sale States",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (state)(gramophile_overseer_sales_by_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(avg by (folder)(recordcollection_recordfolder{folder!=\"1613206\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}