apiVersion: v1
kind: Service
metadata:
  name: overseer
  namespace: gramophile
  labels:
    app: overseer
spec:
  type: NodePort
  metadata:
    labels:
      app: overseer
  ports:
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: overseer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: overseer
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - gramophile
  selector:
    matchLabels:
      app: overseer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer
  namespace: gramophile
spec:
  selector:
    matchLabels:
      app: overseer
  replicas: 1
  template:
    metadata:
      labels:
        app: overseer
    spec:
      containers:
        - name: overseer
          image: registry.brotherlogic-backend.com/brotherlogic/overseer:0.1095.0 # {"$imagepolicy": "flux-system:overseer"}
          ports:
            - containerPort: 8081
          env:
            - name: token
              valueFrom:
                secretKeyRef:
                  name: overseer
                  key: overseer_token
      imagePullSecrets:
        - name: regcred
