// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: classification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comparator int32

const (
	Comparator_COMPARATOR_UNKNOWN                Comparator = 0
	Comparator_COMPARATOR_GREATER_THAN           Comparator = 1
	Comparator_COMPARATOR_GREATER_THAN_OR_EQUALS Comparator = 2
	Comparator_COMPARATOR_LESS_THAN              Comparator = 3
	Comparator_COMPARATOR_LESS_THAN_OR_EQUALS    Comparator = 4
)

// Enum value maps for Comparator.
var (
	Comparator_name = map[int32]string{
		0: "COMPARATOR_UNKNOWN",
		1: "COMPARATOR_GREATER_THAN",
		2: "COMPARATOR_GREATER_THAN_OR_EQUALS",
		3: "COMPARATOR_LESS_THAN",
		4: "COMPARATOR_LESS_THAN_OR_EQUALS",
	}
	Comparator_value = map[string]int32{
		"COMPARATOR_UNKNOWN":                0,
		"COMPARATOR_GREATER_THAN":           1,
		"COMPARATOR_GREATER_THAN_OR_EQUALS": 2,
		"COMPARATOR_LESS_THAN":              3,
		"COMPARATOR_LESS_THAN_OR_EQUALS":    4,
	}
)

func (x Comparator) Enum() *Comparator {
	p := new(Comparator)
	*p = x
	return p
}

func (x Comparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Comparator) Descriptor() protoreflect.EnumDescriptor {
	return file_classification_proto_enumTypes[0].Descriptor()
}

func (Comparator) Type() protoreflect.EnumType {
	return &file_classification_proto_enumTypes[0]
}

func (x Comparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Comparator.Descriptor instead.
func (Comparator) EnumDescriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{0}
}

type BooleanSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanSelector) Reset() {
	*x = BooleanSelector{}
	mi := &file_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanSelector) ProtoMessage() {}

func (x *BooleanSelector) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanSelector.ProtoReflect.Descriptor instead.
func (*BooleanSelector) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{0}
}

func (x *BooleanSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IntSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Threshold     int64                  `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Comp          Comparator             `protobuf:"varint,3,opt,name=comp,proto3,enum=gramophile.Comparator" json:"comp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntSelector) Reset() {
	*x = IntSelector{}
	mi := &file_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntSelector) ProtoMessage() {}

func (x *IntSelector) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntSelector.ProtoReflect.Descriptor instead.
func (*IntSelector) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{1}
}

func (x *IntSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntSelector) GetThreshold() int64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *IntSelector) GetComp() Comparator {
	if x != nil {
		return x.Comp
	}
	return Comparator_COMPARATOR_UNKNOWN
}

type DateSinceSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateSinceSelector) Reset() {
	*x = DateSinceSelector{}
	mi := &file_classification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateSinceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateSinceSelector) ProtoMessage() {}

func (x *DateSinceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateSinceSelector.ProtoReflect.Descriptor instead.
func (*DateSinceSelector) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{2}
}

func (x *DateSinceSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DateSinceSelector) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type LocationSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationSelector) Reset() {
	*x = LocationSelector{}
	mi := &file_classification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationSelector) ProtoMessage() {}

func (x *LocationSelector) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationSelector.ProtoReflect.Descriptor instead.
func (*LocationSelector) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{3}
}

func (x *LocationSelector) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ClassificationRule struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RuleName string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	// Types that are valid to be assigned to Selector:
	//
	//	*ClassificationRule_BooleanSelector
	//	*ClassificationRule_IntSelector
	//	*ClassificationRule_DateSinceSelector
	//	*ClassificationRule_LocationSelector
	Selector      isClassificationRule_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationRule) Reset() {
	*x = ClassificationRule{}
	mi := &file_classification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationRule) ProtoMessage() {}

func (x *ClassificationRule) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationRule.ProtoReflect.Descriptor instead.
func (*ClassificationRule) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{4}
}

func (x *ClassificationRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *ClassificationRule) GetSelector() isClassificationRule_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *ClassificationRule) GetBooleanSelector() *BooleanSelector {
	if x != nil {
		if x, ok := x.Selector.(*ClassificationRule_BooleanSelector); ok {
			return x.BooleanSelector
		}
	}
	return nil
}

func (x *ClassificationRule) GetIntSelector() *IntSelector {
	if x != nil {
		if x, ok := x.Selector.(*ClassificationRule_IntSelector); ok {
			return x.IntSelector
		}
	}
	return nil
}

func (x *ClassificationRule) GetDateSinceSelector() *DateSinceSelector {
	if x != nil {
		if x, ok := x.Selector.(*ClassificationRule_DateSinceSelector); ok {
			return x.DateSinceSelector
		}
	}
	return nil
}

func (x *ClassificationRule) GetLocationSelector() *LocationSelector {
	if x != nil {
		if x, ok := x.Selector.(*ClassificationRule_LocationSelector); ok {
			return x.LocationSelector
		}
	}
	return nil
}

type isClassificationRule_Selector interface {
	isClassificationRule_Selector()
}

type ClassificationRule_BooleanSelector struct {
	BooleanSelector *BooleanSelector `protobuf:"bytes,3,opt,name=boolean_selector,json=booleanSelector,proto3,oneof"`
}

type ClassificationRule_IntSelector struct {
	IntSelector *IntSelector `protobuf:"bytes,4,opt,name=int_selector,json=intSelector,proto3,oneof"`
}

type ClassificationRule_DateSinceSelector struct {
	DateSinceSelector *DateSinceSelector `protobuf:"bytes,5,opt,name=date_since_selector,json=dateSinceSelector,proto3,oneof"`
}

type ClassificationRule_LocationSelector struct {
	LocationSelector *LocationSelector `protobuf:"bytes,6,opt,name=location_selector,json=locationSelector,proto3,oneof"`
}

func (*ClassificationRule_BooleanSelector) isClassificationRule_Selector() {}

func (*ClassificationRule_IntSelector) isClassificationRule_Selector() {}

func (*ClassificationRule_DateSinceSelector) isClassificationRule_Selector() {}

func (*ClassificationRule_LocationSelector) isClassificationRule_Selector() {}

type Classifier struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassifierName string                 `protobuf:"bytes,1,opt,name=classifier_name,json=classifierName,proto3" json:"classifier_name,omitempty"`
	Rules          []*ClassificationRule  `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	Classification string                 `protobuf:"bytes,3,opt,name=classification,proto3" json:"classification,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Classifier) Reset() {
	*x = Classifier{}
	mi := &file_classification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Classifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classifier) ProtoMessage() {}

func (x *Classifier) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classifier.ProtoReflect.Descriptor instead.
func (*Classifier) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{5}
}

func (x *Classifier) GetClassifierName() string {
	if x != nil {
		return x.ClassifierName
	}
	return ""
}

func (x *Classifier) GetRules() []*ClassificationRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Classifier) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *Classifier) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ClassificationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classifiers   []*Classifier          `protobuf:"bytes,1,rep,name=classifiers,proto3" json:"classifiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationConfig) Reset() {
	*x = ClassificationConfig{}
	mi := &file_classification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationConfig) ProtoMessage() {}

func (x *ClassificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationConfig.ProtoReflect.Descriptor instead.
func (*ClassificationConfig) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{6}
}

func (x *ClassificationConfig) GetClassifiers() []*Classifier {
	if x != nil {
		return x.Classifiers
	}
	return nil
}

var File_classification_proto protoreflect.FileDescriptor

const file_classification_proto_rawDesc = "" +
	"\n" +
	"\x14classification.proto\x12\n" +
	"gramophile\"%\n" +
	"\x0fBooleanSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"k\n" +
	"\vIntSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x03R\tthreshold\x12*\n" +
	"\x04comp\x18\x03 \x01(\x0e2\x16.gramophile.ComparatorR\x04comp\"C\n" +
	"\x11DateSinceSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\".\n" +
	"\x10LocationSelector\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"\xe3\x02\n" +
	"\x12ClassificationRule\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12H\n" +
	"\x10boolean_selector\x18\x03 \x01(\v2\x1b.gramophile.BooleanSelectorH\x00R\x0fbooleanSelector\x12<\n" +
	"\fint_selector\x18\x04 \x01(\v2\x17.gramophile.IntSelectorH\x00R\vintSelector\x12O\n" +
	"\x13date_since_selector\x18\x05 \x01(\v2\x1d.gramophile.DateSinceSelectorH\x00R\x11dateSinceSelector\x12K\n" +
	"\x11location_selector\x18\x06 \x01(\v2\x1c.gramophile.LocationSelectorH\x00R\x10locationSelectorB\n" +
	"\n" +
	"\bselector\"\xaf\x01\n" +
	"\n" +
	"Classifier\x12'\n" +
	"\x0fclassifier_name\x18\x01 \x01(\tR\x0eclassifierName\x124\n" +
	"\x05rules\x18\x02 \x03(\v2\x1e.gramophile.ClassificationRuleR\x05rules\x12&\n" +
	"\x0eclassification\x18\x03 \x01(\tR\x0eclassification\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"P\n" +
	"\x14ClassificationConfig\x128\n" +
	"\vclassifiers\x18\x01 \x03(\v2\x16.gramophile.ClassifierR\vclassifiers*\xa6\x01\n" +
	"\n" +
	"Comparator\x12\x16\n" +
	"\x12COMPARATOR_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17COMPARATOR_GREATER_THAN\x10\x01\x12%\n" +
	"!COMPARATOR_GREATER_THAN_OR_EQUALS\x10\x02\x12\x18\n" +
	"\x14COMPARATOR_LESS_THAN\x10\x03\x12\"\n" +
	"\x1eCOMPARATOR_LESS_THAN_OR_EQUALS\x10\x04B*Z(github.com/brotherlogic/gramophile/protob\x06proto3"

var (
	file_classification_proto_rawDescOnce sync.Once
	file_classification_proto_rawDescData []byte
)

func file_classification_proto_rawDescGZIP() []byte {
	file_classification_proto_rawDescOnce.Do(func() {
		file_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classification_proto_rawDesc), len(file_classification_proto_rawDesc)))
	})
	return file_classification_proto_rawDescData
}

var file_classification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_classification_proto_goTypes = []any{
	(Comparator)(0),              // 0: gramophile.Comparator
	(*BooleanSelector)(nil),      // 1: gramophile.BooleanSelector
	(*IntSelector)(nil),          // 2: gramophile.IntSelector
	(*DateSinceSelector)(nil),    // 3: gramophile.DateSinceSelector
	(*LocationSelector)(nil),     // 4: gramophile.LocationSelector
	(*ClassificationRule)(nil),   // 5: gramophile.ClassificationRule
	(*Classifier)(nil),           // 6: gramophile.Classifier
	(*ClassificationConfig)(nil), // 7: gramophile.ClassificationConfig
}
var file_classification_proto_depIdxs = []int32{
	0, // 0: gramophile.IntSelector.comp:type_name -> gramophile.Comparator
	1, // 1: gramophile.ClassificationRule.boolean_selector:type_name -> gramophile.BooleanSelector
	2, // 2: gramophile.ClassificationRule.int_selector:type_name -> gramophile.IntSelector
	3, // 3: gramophile.ClassificationRule.date_since_selector:type_name -> gramophile.DateSinceSelector
	4, // 4: gramophile.ClassificationRule.location_selector:type_name -> gramophile.LocationSelector
	5, // 5: gramophile.Classifier.rules:type_name -> gramophile.ClassificationRule
	6, // 6: gramophile.ClassificationConfig.classifiers:type_name -> gramophile.Classifier
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_classification_proto_init() }
func file_classification_proto_init() {
	if File_classification_proto != nil {
		return
	}
	file_classification_proto_msgTypes[4].OneofWrappers = []any{
		(*ClassificationRule_BooleanSelector)(nil),
		(*ClassificationRule_IntSelector)(nil),
		(*ClassificationRule_DateSinceSelector)(nil),
		(*ClassificationRule_LocationSelector)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classification_proto_rawDesc), len(file_classification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_classification_proto_goTypes,
		DependencyIndexes: file_classification_proto_depIdxs,
		EnumInfos:         file_classification_proto_enumTypes,
		MessageInfos:      file_classification_proto_msgTypes,
	}.Build()
	File_classification_proto = out.File
	file_classification_proto_goTypes = nil
	file_classification_proto_depIdxs = nil
}
