// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Basis int32

const (
	Basis_DISCOGS    Basis = 0
	Basis_GRAMOPHILE Basis = 1
)

// Enum value maps for Basis.
var (
	Basis_name = map[int32]string{
		0: "DISCOGS",
		1: "GRAMOPHILE",
	}
	Basis_value = map[string]int32{
		"DISCOGS":    0,
		"GRAMOPHILE": 1,
	}
)

func (x Basis) Enum() *Basis {
	p := new(Basis)
	*p = x
	return p
}

func (x Basis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Basis) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (Basis) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x Basis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Basis.Descriptor instead.
func (Basis) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type Mandate int32

const (
	Mandate_NONE        Mandate = 0
	Mandate_RECOMMENDED Mandate = 1
	Mandate_REQUIRED    Mandate = 2
)

// Enum value maps for Mandate.
var (
	Mandate_name = map[int32]string{
		0: "NONE",
		1: "RECOMMENDED",
		2: "REQUIRED",
	}
	Mandate_value = map[string]int32{
		"NONE":        0,
		"RECOMMENDED": 1,
		"REQUIRED":    2,
	}
)

func (x Mandate) Enum() *Mandate {
	p := new(Mandate)
	*p = x
	return p
}

func (x Mandate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mandate) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (Mandate) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x Mandate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mandate.Descriptor instead.
func (Mandate) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Formats []string `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

type CleaningConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cleaning             Mandate `protobuf:"varint,1,opt,name=cleaning,proto3,enum=gramophile.Mandate" json:"cleaning,omitempty"`
	AppliesTo            *Filter `protobuf:"bytes,2,opt,name=applies_to,json=appliesTo,proto3" json:"applies_to,omitempty"`
	CleaningGapInSeconds int64   `protobuf:"varint,3,opt,name=cleaning_gap_in_seconds,json=cleaningGapInSeconds,proto3" json:"cleaning_gap_in_seconds,omitempty"`
	CleaningGapInPlays   int32   `protobuf:"varint,4,opt,name=cleaning_gap_in_plays,json=cleaningGapInPlays,proto3" json:"cleaning_gap_in_plays,omitempty"`
}

func (x *CleaningConfig) Reset() {
	*x = CleaningConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleaningConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleaningConfig) ProtoMessage() {}

func (x *CleaningConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleaningConfig.ProtoReflect.Descriptor instead.
func (*CleaningConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *CleaningConfig) GetCleaning() Mandate {
	if x != nil {
		return x.Cleaning
	}
	return Mandate_NONE
}

func (x *CleaningConfig) GetAppliesTo() *Filter {
	if x != nil {
		return x.AppliesTo
	}
	return nil
}

func (x *CleaningConfig) GetCleaningGapInSeconds() int64 {
	if x != nil {
		return x.CleaningGapInSeconds
	}
	return 0
}

func (x *CleaningConfig) GetCleaningGapInPlays() int32 {
	if x != nil {
		return x.CleaningGapInPlays
	}
	return 0
}

type GramophileConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basis          Basis           `protobuf:"varint,2,opt,name=basis,proto3,enum=gramophile.Basis" json:"basis,omitempty"`
	CleaningConfig *CleaningConfig `protobuf:"bytes,1,opt,name=cleaning_config,json=cleaningConfig,proto3" json:"cleaning_config,omitempty"`
}

func (x *GramophileConfig) Reset() {
	*x = GramophileConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GramophileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GramophileConfig) ProtoMessage() {}

func (x *GramophileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GramophileConfig.ProtoReflect.Descriptor instead.
func (*GramophileConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *GramophileConfig) GetBasis() Basis {
	if x != nil {
		return x.Basis
	}
	return Basis_DISCOGS
}

func (x *GramophileConfig) GetCleaningConfig() *CleaningConfig {
	if x != nil {
		return x.CleaningConfig
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

var file_config_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68, 0x69, 0x6c, 0x65, 0x22, 0x22, 0x0a, 0x06, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x22, 0xde,
	0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68, 0x69, 0x6c, 0x65,
	0x2e, 0x4d, 0x61, 0x6e, 0x64, 0x61, 0x74, 0x65, 0x52, 0x08, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x73, 0x5f, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68,
	0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x09, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x73, 0x54, 0x6f, 0x12, 0x35, 0x0a, 0x17, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e,
	0x67, 0x5f, 0x67, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67,
	0x47, 0x61, 0x70, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x15,
	0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x67, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x5f,
	0x70, 0x6c, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x63, 0x6c, 0x65,
	0x61, 0x6e, 0x69, 0x6e, 0x67, 0x47, 0x61, 0x70, 0x49, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x22,
	0x80, 0x01, 0x0a, 0x10, 0x47, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68, 0x69, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68, 0x69, 0x6c, 0x65,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x73, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69, 0x73, 0x12, 0x43, 0x0a,
	0x0f, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68,
	0x69, 0x6c, 0x65, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x0e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2a, 0x24, 0x0a, 0x05, 0x42, 0x61, 0x73, 0x69, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x49, 0x53, 0x43, 0x4f, 0x47, 0x53, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x52, 0x41, 0x4d,
	0x4f, 0x50, 0x48, 0x49, 0x4c, 0x45, 0x10, 0x01, 0x2a, 0x32, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x52, 0x45, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x67, 0x72, 0x61, 0x6d, 0x6f, 0x70, 0x68, 0x69,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_proto_goTypes = []interface{}{
	(Basis)(0),               // 0: gramophile.Basis
	(Mandate)(0),             // 1: gramophile.Mandate
	(*Filter)(nil),           // 2: gramophile.Filter
	(*CleaningConfig)(nil),   // 3: gramophile.CleaningConfig
	(*GramophileConfig)(nil), // 4: gramophile.GramophileConfig
}
var file_config_proto_depIdxs = []int32{
	1, // 0: gramophile.CleaningConfig.cleaning:type_name -> gramophile.Mandate
	2, // 1: gramophile.CleaningConfig.applies_to:type_name -> gramophile.Filter
	0, // 2: gramophile.GramophileConfig.basis:type_name -> gramophile.Basis
	3, // 3: gramophile.GramophileConfig.cleaning_config:type_name -> gramophile.CleaningConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleaningConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GramophileConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
