// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: moving.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormatSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Description   []string               `protobuf:"bytes,2,rep,name=description,proto3" json:"description,omitempty"`
	Contains      []string               `protobuf:"bytes,3,rep,name=contains,proto3" json:"contains,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatSelector) Reset() {
	*x = FormatSelector{}
	mi := &file_moving_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatSelector) ProtoMessage() {}

func (x *FormatSelector) ProtoReflect() protoreflect.Message {
	mi := &file_moving_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatSelector.ProtoReflect.Descriptor instead.
func (*FormatSelector) Descriptor() ([]byte, []int) {
	return file_moving_proto_rawDescGZIP(), []int{0}
}

func (x *FormatSelector) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *FormatSelector) GetDescription() []string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *FormatSelector) GetContains() []string {
	if x != nil {
		return x.Contains
	}
	return nil
}

func (x *FormatSelector) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type FormatClassifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Formats       []*FormatSelector      `protobuf:"bytes,1,rep,name=formats,proto3" json:"formats,omitempty"`
	DefaultFormat string                 `protobuf:"bytes,2,opt,name=default_format,json=defaultFormat,proto3" json:"default_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatClassifier) Reset() {
	*x = FormatClassifier{}
	mi := &file_moving_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatClassifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatClassifier) ProtoMessage() {}

func (x *FormatClassifier) ProtoReflect() protoreflect.Message {
	mi := &file_moving_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatClassifier.ProtoReflect.Descriptor instead.
func (*FormatClassifier) Descriptor() ([]byte, []int) {
	return file_moving_proto_rawDescGZIP(), []int{1}
}

func (x *FormatClassifier) GetFormats() []*FormatSelector {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *FormatClassifier) GetDefaultFormat() string {
	if x != nil {
		return x.DefaultFormat
	}
	return ""
}

type RecordMove struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Classification []string               `protobuf:"bytes,2,rep,name=classification,proto3" json:"classification,omitempty"`
	Format         []string               `protobuf:"bytes,3,rep,name=format,proto3" json:"format,omitempty"`
	Folder         string                 `protobuf:"bytes,4,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordMove) Reset() {
	*x = RecordMove{}
	mi := &file_moving_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMove) ProtoMessage() {}

func (x *RecordMove) ProtoReflect() protoreflect.Message {
	mi := &file_moving_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMove.ProtoReflect.Descriptor instead.
func (*RecordMove) Descriptor() ([]byte, []int) {
	return file_moving_proto_rawDescGZIP(), []int{2}
}

func (x *RecordMove) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordMove) GetClassification() []string {
	if x != nil {
		return x.Classification
	}
	return nil
}

func (x *RecordMove) GetFormat() []string {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *RecordMove) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type MovingConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FormatClassifier *FormatClassifier      `protobuf:"bytes,1,opt,name=format_classifier,json=formatClassifier,proto3" json:"format_classifier,omitempty"`
	Moves            []*RecordMove          `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	Enabled          bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MovingConfig) Reset() {
	*x = MovingConfig{}
	mi := &file_moving_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovingConfig) ProtoMessage() {}

func (x *MovingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_moving_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovingConfig.ProtoReflect.Descriptor instead.
func (*MovingConfig) Descriptor() ([]byte, []int) {
	return file_moving_proto_rawDescGZIP(), []int{3}
}

func (x *MovingConfig) GetFormatClassifier() *FormatClassifier {
	if x != nil {
		return x.FormatClassifier
	}
	return nil
}

func (x *MovingConfig) GetMoves() []*RecordMove {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *MovingConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_moving_proto protoreflect.FileDescriptor

const file_moving_proto_rawDesc = "" +
	"\n" +
	"\fmoving.proto\x12\n" +
	"gramophile\"|\n" +
	"\x0eFormatSelector\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12 \n" +
	"\vdescription\x18\x02 \x03(\tR\vdescription\x12\x1a\n" +
	"\bcontains\x18\x03 \x03(\tR\bcontains\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\"o\n" +
	"\x10FormatClassifier\x124\n" +
	"\aformats\x18\x01 \x03(\v2\x1a.gramophile.FormatSelectorR\aformats\x12%\n" +
	"\x0edefault_format\x18\x02 \x01(\tR\rdefaultFormat\"x\n" +
	"\n" +
	"RecordMove\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x0eclassification\x18\x02 \x03(\tR\x0eclassification\x12\x16\n" +
	"\x06format\x18\x03 \x03(\tR\x06format\x12\x16\n" +
	"\x06folder\x18\x04 \x01(\tR\x06folder\"\xa1\x01\n" +
	"\fMovingConfig\x12I\n" +
	"\x11format_classifier\x18\x01 \x01(\v2\x1c.gramophile.FormatClassifierR\x10formatClassifier\x12,\n" +
	"\x05moves\x18\x02 \x03(\v2\x16.gramophile.RecordMoveR\x05moves\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabledB*Z(github.com/brotherlogic/gramophile/protob\x06proto3"

var (
	file_moving_proto_rawDescOnce sync.Once
	file_moving_proto_rawDescData []byte
)

func file_moving_proto_rawDescGZIP() []byte {
	file_moving_proto_rawDescOnce.Do(func() {
		file_moving_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moving_proto_rawDesc), len(file_moving_proto_rawDesc)))
	})
	return file_moving_proto_rawDescData
}

var file_moving_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_moving_proto_goTypes = []any{
	(*FormatSelector)(nil),   // 0: gramophile.FormatSelector
	(*FormatClassifier)(nil), // 1: gramophile.FormatClassifier
	(*RecordMove)(nil),       // 2: gramophile.RecordMove
	(*MovingConfig)(nil),     // 3: gramophile.MovingConfig
}
var file_moving_proto_depIdxs = []int32{
	0, // 0: gramophile.FormatClassifier.formats:type_name -> gramophile.FormatSelector
	1, // 1: gramophile.MovingConfig.format_classifier:type_name -> gramophile.FormatClassifier
	2, // 2: gramophile.MovingConfig.moves:type_name -> gramophile.RecordMove
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moving_proto_init() }
func file_moving_proto_init() {
	if File_moving_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moving_proto_rawDesc), len(file_moving_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moving_proto_goTypes,
		DependencyIndexes: file_moving_proto_depIdxs,
		MessageInfos:      file_moving_proto_msgTypes,
	}.Build()
	File_moving_proto = out.File
	file_moving_proto_goTypes = nil
	file_moving_proto_depIdxs = nil
}
