// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: organisation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissingWidthHandling int32

const (
	MissingWidthHandling_MISSING_WIDTH_IGNORE  MissingWidthHandling = 0
	MissingWidthHandling_MISSING_WIDTH_AVERAGE MissingWidthHandling = 1
)

// Enum value maps for MissingWidthHandling.
var (
	MissingWidthHandling_name = map[int32]string{
		0: "MISSING_WIDTH_IGNORE",
		1: "MISSING_WIDTH_AVERAGE",
	}
	MissingWidthHandling_value = map[string]int32{
		"MISSING_WIDTH_IGNORE":  0,
		"MISSING_WIDTH_AVERAGE": 1,
	}
)

func (x MissingWidthHandling) Enum() *MissingWidthHandling {
	p := new(MissingWidthHandling)
	*p = x
	return p
}

func (x MissingWidthHandling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissingWidthHandling) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[0].Descriptor()
}

func (MissingWidthHandling) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[0]
}

func (x MissingWidthHandling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MissingWidthHandling.Descriptor instead.
func (MissingWidthHandling) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{0}
}

type Sort int32

const (
	Sort_ARTIST_YEAR           Sort = 0
	Sort_LABEL_CATNO           Sort = 1
	Sort_RELEASE_YEAR          Sort = 2
	Sort_EARLIEST_RELEASE_YEAR Sort = 3
	Sort_ADDITION_DATE         Sort = 4
)

// Enum value maps for Sort.
var (
	Sort_name = map[int32]string{
		0: "ARTIST_YEAR",
		1: "LABEL_CATNO",
		2: "RELEASE_YEAR",
		3: "EARLIEST_RELEASE_YEAR",
		4: "ADDITION_DATE",
	}
	Sort_value = map[string]int32{
		"ARTIST_YEAR":           0,
		"LABEL_CATNO":           1,
		"RELEASE_YEAR":          2,
		"EARLIEST_RELEASE_YEAR": 3,
		"ADDITION_DATE":         4,
	}
)

func (x Sort) Enum() *Sort {
	p := new(Sort)
	*p = x
	return p
}

func (x Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[1].Descriptor()
}

func (Sort) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[1]
}

func (x Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort.Descriptor instead.
func (Sort) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{1}
}

type Layout int32

const (
	Layout_TIGHT Layout = 0
	Layout_LOOSE Layout = 1 // Currently unsupported
)

// Enum value maps for Layout.
var (
	Layout_name = map[int32]string{
		0: "TIGHT",
		1: "LOOSE",
	}
	Layout_value = map[string]int32{
		"TIGHT": 0,
		"LOOSE": 1,
	}
)

func (x Layout) Enum() *Layout {
	p := new(Layout)
	*p = x
	return p
}

func (x Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[2].Descriptor()
}

func (Layout) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[2]
}

func (x Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layout.Descriptor instead.
func (Layout) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{2}
}

type Density int32

const (
	Density_COUNT Density = 0
	Density_DISKS Density = 1
	Density_WIDTH Density = 2
)

// Enum value maps for Density.
var (
	Density_name = map[int32]string{
		0: "COUNT",
		1: "DISKS",
		2: "WIDTH",
	}
	Density_value = map[string]int32{
		"COUNT": 0,
		"DISKS": 1,
		"WIDTH": 2,
	}
)

func (x Density) Enum() *Density {
	p := new(Density)
	*p = x
	return p
}

func (x Density) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Density) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[3].Descriptor()
}

func (Density) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[3]
}

func (x Density) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Density.Descriptor instead.
func (Density) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{3}
}

type OrganisationUse int32

const (
	OrganisationUse_ORG_USE_UNKNOWN   OrganisationUse = 0
	OrganisationUse_ORG_USE_LISTENING OrganisationUse = 1
)

// Enum value maps for OrganisationUse.
var (
	OrganisationUse_name = map[int32]string{
		0: "ORG_USE_UNKNOWN",
		1: "ORG_USE_LISTENING",
	}
	OrganisationUse_value = map[string]int32{
		"ORG_USE_UNKNOWN":   0,
		"ORG_USE_LISTENING": 1,
	}
)

func (x OrganisationUse) Enum() *OrganisationUse {
	p := new(OrganisationUse)
	*p = x
	return p
}

func (x OrganisationUse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganisationUse) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[4].Descriptor()
}

func (OrganisationUse) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[4]
}

func (x OrganisationUse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganisationUse.Descriptor instead.
func (OrganisationUse) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{4}
}

type GroupSpill int32

const (
	GroupSpill_SPILL_NO_SPILL       GroupSpill = 0
	GroupSpill_SPILL_BREAK_ORDERING GroupSpill = 1
)

// Enum value maps for GroupSpill.
var (
	GroupSpill_name = map[int32]string{
		0: "SPILL_NO_SPILL",
		1: "SPILL_BREAK_ORDERING",
	}
	GroupSpill_value = map[string]int32{
		"SPILL_NO_SPILL":       0,
		"SPILL_BREAK_ORDERING": 1,
	}
)

func (x GroupSpill) Enum() *GroupSpill {
	p := new(GroupSpill)
	*p = x
	return p
}

func (x GroupSpill) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupSpill) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[5].Descriptor()
}

func (GroupSpill) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[5]
}

func (x GroupSpill) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupSpill.Descriptor instead.
func (GroupSpill) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{5}
}

type GroupingType int32

const (
	GroupingType_GROUPING_NO_GROUPING GroupingType = 0
	GroupingType_GROUPING_GROUP       GroupingType = 1
)

// Enum value maps for GroupingType.
var (
	GroupingType_name = map[int32]string{
		0: "GROUPING_NO_GROUPING",
		1: "GROUPING_GROUP",
	}
	GroupingType_value = map[string]int32{
		"GROUPING_NO_GROUPING": 0,
		"GROUPING_GROUP":       1,
	}
)

func (x GroupingType) Enum() *GroupingType {
	p := new(GroupingType)
	*p = x
	return p
}

func (x GroupingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupingType) Descriptor() protoreflect.EnumDescriptor {
	return file_organisation_proto_enumTypes[6].Descriptor()
}

func (GroupingType) Type() protoreflect.EnumType {
	return &file_organisation_proto_enumTypes[6]
}

func (x GroupingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupingType.Descriptor instead.
func (GroupingType) EnumDescriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{6}
}

type OrganisationConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ArtistTranslation []*ArtistTranslation   `protobuf:"bytes,1,rep,name=artist_translation,json=artistTranslation,proto3" json:"artist_translation,omitempty"`
	Organisations     []*Organisation        `protobuf:"bytes,2,rep,name=organisations,proto3" json:"organisations,omitempty"`
	LabelRanking      []*LabelWeight         `protobuf:"bytes,3,rep,name=label_ranking,json=labelRanking,proto3" json:"label_ranking,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OrganisationConfig) Reset() {
	*x = OrganisationConfig{}
	mi := &file_organisation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganisationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganisationConfig) ProtoMessage() {}

func (x *OrganisationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganisationConfig.ProtoReflect.Descriptor instead.
func (*OrganisationConfig) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{0}
}

func (x *OrganisationConfig) GetArtistTranslation() []*ArtistTranslation {
	if x != nil {
		return x.ArtistTranslation
	}
	return nil
}

func (x *OrganisationConfig) GetOrganisations() []*Organisation {
	if x != nil {
		return x.Organisations
	}
	return nil
}

func (x *OrganisationConfig) GetLabelRanking() []*LabelWeight {
	if x != nil {
		return x.LabelRanking
	}
	return nil
}

type OrganisationSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          int64                  `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Placements    []*Placement           `protobuf:"bytes,2,rep,name=placements,proto3" json:"placements,omitempty"`
	Hash          string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganisationSnapshot) Reset() {
	*x = OrganisationSnapshot{}
	mi := &file_organisation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganisationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganisationSnapshot) ProtoMessage() {}

func (x *OrganisationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganisationSnapshot.ProtoReflect.Descriptor instead.
func (*OrganisationSnapshot) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{1}
}

func (x *OrganisationSnapshot) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *OrganisationSnapshot) GetPlacements() []*Placement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *OrganisationSnapshot) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *OrganisationSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SnapshotDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotDiff) Reset() {
	*x = SnapshotDiff{}
	mi := &file_organisation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDiff) ProtoMessage() {}

func (x *SnapshotDiff) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDiff.ProtoReflect.Descriptor instead.
func (*SnapshotDiff) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotDiff) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *Placement             `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *Placement             `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_organisation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{3}
}

func (x *Move) GetStart() *Placement {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Move) GetEnd() *Placement {
	if x != nil {
		return x.End
	}
	return nil
}

type Placement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Iid   int64                  `protobuf:"varint,1,opt,name=iid,proto3" json:"iid,omitempty"`
	Unit  int32                  `protobuf:"varint,2,opt,name=unit,proto3" json:"unit,omitempty"`
	Index int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Space string                 `protobuf:"bytes,4,opt,name=space,proto3" json:"space,omitempty"`
	Width float32                `protobuf:"fixed32,5,opt,name=width,proto3" json:"width,omitempty"`
	// This is the unfiltered index
	OriginalIndex int32  `protobuf:"varint,7,opt,name=original_index,json=originalIndex,proto3" json:"original_index,omitempty"`
	Observations  string `protobuf:"bytes,8,opt,name=observations,proto3" json:"observations,omitempty"`
	// Optional
	SortKey       string `protobuf:"bytes,6,opt,name=sort_key,json=sortKey,proto3" json:"sort_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placement) Reset() {
	*x = Placement{}
	mi := &file_organisation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placement) ProtoMessage() {}

func (x *Placement) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placement.ProtoReflect.Descriptor instead.
func (*Placement) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{4}
}

func (x *Placement) GetIid() int64 {
	if x != nil {
		return x.Iid
	}
	return 0
}

func (x *Placement) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *Placement) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Placement) GetSpace() string {
	if x != nil {
		return x.Space
	}
	return ""
}

func (x *Placement) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Placement) GetOriginalIndex() int32 {
	if x != nil {
		return x.OriginalIndex
	}
	return 0
}

func (x *Placement) GetObservations() string {
	if x != nil {
		return x.Observations
	}
	return ""
}

func (x *Placement) GetSortKey() string {
	if x != nil {
		return x.SortKey
	}
	return ""
}

type Organisation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Foldersets           []*FolderSet           `protobuf:"bytes,1,rep,name=foldersets,proto3" json:"foldersets,omitempty"`
	Spaces               []*Space               `protobuf:"bytes,2,rep,name=spaces,proto3" json:"spaces,omitempty"`
	AutoArtistTranslate  bool                   `protobuf:"varint,5,opt,name=auto_artist_translate,json=autoArtistTranslate,proto3" json:"auto_artist_translate,omitempty"`
	Density              Density                `protobuf:"varint,3,opt,name=density,proto3,enum=gramophile.Density" json:"density,omitempty"`
	MissingWidthHandling MissingWidthHandling   `protobuf:"varint,8,opt,name=missing_width_handling,json=missingWidthHandling,proto3,enum=gramophile.MissingWidthHandling" json:"missing_width_handling,omitempty"`
	Grouping             *Grouping              `protobuf:"bytes,4,opt,name=grouping,proto3" json:"grouping,omitempty"`
	Spill                *Spill                 `protobuf:"bytes,7,opt,name=spill,proto3" json:"spill,omitempty"`
	Use                  OrganisationUse        `protobuf:"varint,9,opt,name=use,proto3,enum=gramophile.OrganisationUse" json:"use,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Organisation) Reset() {
	*x = Organisation{}
	mi := &file_organisation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organisation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organisation) ProtoMessage() {}

func (x *Organisation) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organisation.ProtoReflect.Descriptor instead.
func (*Organisation) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{5}
}

func (x *Organisation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organisation) GetFoldersets() []*FolderSet {
	if x != nil {
		return x.Foldersets
	}
	return nil
}

func (x *Organisation) GetSpaces() []*Space {
	if x != nil {
		return x.Spaces
	}
	return nil
}

func (x *Organisation) GetAutoArtistTranslate() bool {
	if x != nil {
		return x.AutoArtistTranslate
	}
	return false
}

func (x *Organisation) GetDensity() Density {
	if x != nil {
		return x.Density
	}
	return Density_COUNT
}

func (x *Organisation) GetMissingWidthHandling() MissingWidthHandling {
	if x != nil {
		return x.MissingWidthHandling
	}
	return MissingWidthHandling_MISSING_WIDTH_IGNORE
}

func (x *Organisation) GetGrouping() *Grouping {
	if x != nil {
		return x.Grouping
	}
	return nil
}

func (x *Organisation) GetSpill() *Spill {
	if x != nil {
		return x.Spill
	}
	return nil
}

func (x *Organisation) GetUse() OrganisationUse {
	if x != nil {
		return x.Use
	}
	return OrganisationUse_ORG_USE_UNKNOWN
}

type Spill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  GroupSpill             `protobuf:"varint,1,opt,name=type,proto3,enum=gramophile.GroupSpill" json:"type,omitempty"`
	// -1 means an infinite look ahead
	LookAhead     int32 `protobuf:"varint,2,opt,name=look_ahead,json=lookAhead,proto3" json:"look_ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spill) Reset() {
	*x = Spill{}
	mi := &file_organisation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spill) ProtoMessage() {}

func (x *Spill) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spill.ProtoReflect.Descriptor instead.
func (*Spill) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{6}
}

func (x *Spill) GetType() GroupSpill {
	if x != nil {
		return x.Type
	}
	return GroupSpill_SPILL_NO_SPILL
}

func (x *Spill) GetLookAhead() int32 {
	if x != nil {
		return x.LookAhead
	}
	return 0
}

type ArtistMapping struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaderArtist    string                 `protobuf:"bytes,1,opt,name=leader_artist,json=leaderArtist,proto3" json:"leader_artist,omitempty"`
	FollowingArtist []string               `protobuf:"bytes,2,rep,name=following_artist,json=followingArtist,proto3" json:"following_artist,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArtistMapping) Reset() {
	*x = ArtistMapping{}
	mi := &file_organisation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistMapping) ProtoMessage() {}

func (x *ArtistMapping) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistMapping.ProtoReflect.Descriptor instead.
func (*ArtistMapping) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{7}
}

func (x *ArtistMapping) GetLeaderArtist() string {
	if x != nil {
		return x.LeaderArtist
	}
	return ""
}

func (x *ArtistMapping) GetFollowingArtist() []string {
	if x != nil {
		return x.FollowingArtist
	}
	return nil
}

type Grouping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GroupingType           `protobuf:"varint,1,opt,name=type,proto3,enum=gramophile.GroupingType" json:"type,omitempty"`
	ArtistWeights []*ArtistWeight        `protobuf:"bytes,2,rep,name=artist_weights,json=artistWeights,proto3" json:"artist_weights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grouping) Reset() {
	*x = Grouping{}
	mi := &file_organisation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grouping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grouping) ProtoMessage() {}

func (x *Grouping) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grouping.ProtoReflect.Descriptor instead.
func (*Grouping) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{8}
}

func (x *Grouping) GetType() GroupingType {
	if x != nil {
		return x.Type
	}
	return GroupingType_GROUPING_NO_GROUPING
}

func (x *Grouping) GetArtistWeights() []*ArtistWeight {
	if x != nil {
		return x.ArtistWeights
	}
	return nil
}

type LabelWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelId       int32                  `protobuf:"varint,1,opt,name=label_id,json=labelId,proto3" json:"label_id,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"` // Default weight is 0.5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelWeight) Reset() {
	*x = LabelWeight{}
	mi := &file_organisation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelWeight) ProtoMessage() {}

func (x *LabelWeight) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelWeight.ProtoReflect.Descriptor instead.
func (*LabelWeight) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{9}
}

func (x *LabelWeight) GetLabelId() int32 {
	if x != nil {
		return x.LabelId
	}
	return 0
}

func (x *LabelWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ArtistWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistId      int32                  `protobuf:"varint,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistWeight) Reset() {
	*x = ArtistWeight{}
	mi := &file_organisation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistWeight) ProtoMessage() {}

func (x *ArtistWeight) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistWeight.ProtoReflect.Descriptor instead.
func (*ArtistWeight) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{10}
}

func (x *ArtistWeight) GetArtistId() int32 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

func (x *ArtistWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Space struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Units         int32                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`
	Width         float32                `protobuf:"fixed32,5,opt,name=width,proto3" json:"width,omitempty"`
	Layout        Layout                 `protobuf:"varint,7,opt,name=layout,proto3,enum=gramophile.Layout" json:"layout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_organisation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{11}
}

func (x *Space) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Space) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Space) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Space) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Space) GetLayout() Layout {
	if x != nil {
		return x.Layout
	}
	return Layout_TIGHT
}

type FolderSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Folder        int32                  `protobuf:"varint,3,opt,name=folder,proto3" json:"folder,omitempty"`
	Sort          Sort                   `protobuf:"varint,4,opt,name=sort,proto3,enum=gramophile.Sort" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderSet) Reset() {
	*x = FolderSet{}
	mi := &file_organisation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderSet) ProtoMessage() {}

func (x *FolderSet) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderSet.ProtoReflect.Descriptor instead.
func (*FolderSet) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{12}
}

func (x *FolderSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FolderSet) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FolderSet) GetFolder() int32 {
	if x != nil {
		return x.Folder
	}
	return 0
}

func (x *FolderSet) GetSort() Sort {
	if x != nil {
		return x.Sort
	}
	return Sort_ARTIST_YEAR
}

type ArtistTranslation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtistPrefix  string                 `protobuf:"bytes,1,opt,name=artist_prefix,json=artistPrefix,proto3" json:"artist_prefix,omitempty"`
	OrderedArtist string                 `protobuf:"bytes,2,opt,name=ordered_artist,json=orderedArtist,proto3" json:"ordered_artist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistTranslation) Reset() {
	*x = ArtistTranslation{}
	mi := &file_organisation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistTranslation) ProtoMessage() {}

func (x *ArtistTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_organisation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistTranslation.ProtoReflect.Descriptor instead.
func (*ArtistTranslation) Descriptor() ([]byte, []int) {
	return file_organisation_proto_rawDescGZIP(), []int{13}
}

func (x *ArtistTranslation) GetArtistPrefix() string {
	if x != nil {
		return x.ArtistPrefix
	}
	return ""
}

func (x *ArtistTranslation) GetOrderedArtist() string {
	if x != nil {
		return x.OrderedArtist
	}
	return ""
}

var File_organisation_proto protoreflect.FileDescriptor

const file_organisation_proto_rawDesc = "" +
	"\n" +
	"\x12organisation.proto\x12\n" +
	"gramophile\"\xe0\x01\n" +
	"\x12OrganisationConfig\x12L\n" +
	"\x12artist_translation\x18\x01 \x03(\v2\x1d.gramophile.ArtistTranslationR\x11artistTranslation\x12>\n" +
	"\rorganisations\x18\x02 \x03(\v2\x18.gramophile.OrganisationR\rorganisations\x12<\n" +
	"\rlabel_ranking\x18\x03 \x03(\v2\x17.gramophile.LabelWeightR\flabelRanking\"\x89\x01\n" +
	"\x14OrganisationSnapshot\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x03R\x04date\x125\n" +
	"\n" +
	"placements\x18\x02 \x03(\v2\x15.gramophile.PlacementR\n" +
	"placements\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"6\n" +
	"\fSnapshotDiff\x12&\n" +
	"\x05moves\x18\x01 \x03(\v2\x10.gramophile.MoveR\x05moves\"\\\n" +
	"\x04Move\x12+\n" +
	"\x05start\x18\x01 \x01(\v2\x15.gramophile.PlacementR\x05start\x12'\n" +
	"\x03end\x18\x02 \x01(\v2\x15.gramophile.PlacementR\x03end\"\xd9\x01\n" +
	"\tPlacement\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\x03R\x03iid\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\x05R\x04unit\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x14\n" +
	"\x05space\x18\x04 \x01(\tR\x05space\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x02R\x05width\x12%\n" +
	"\x0eoriginal_index\x18\a \x01(\x05R\roriginalIndex\x12\"\n" +
	"\fobservations\x18\b \x01(\tR\fobservations\x12\x19\n" +
	"\bsort_key\x18\x06 \x01(\tR\asortKey\"\xc9\x03\n" +
	"\fOrganisation\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x125\n" +
	"\n" +
	"foldersets\x18\x01 \x03(\v2\x15.gramophile.FolderSetR\n" +
	"foldersets\x12)\n" +
	"\x06spaces\x18\x02 \x03(\v2\x11.gramophile.SpaceR\x06spaces\x122\n" +
	"\x15auto_artist_translate\x18\x05 \x01(\bR\x13autoArtistTranslate\x12-\n" +
	"\adensity\x18\x03 \x01(\x0e2\x13.gramophile.DensityR\adensity\x12V\n" +
	"\x16missing_width_handling\x18\b \x01(\x0e2 .gramophile.MissingWidthHandlingR\x14missingWidthHandling\x120\n" +
	"\bgrouping\x18\x04 \x01(\v2\x14.gramophile.GroupingR\bgrouping\x12'\n" +
	"\x05spill\x18\a \x01(\v2\x11.gramophile.SpillR\x05spill\x12-\n" +
	"\x03use\x18\t \x01(\x0e2\x1b.gramophile.OrganisationUseR\x03use\"R\n" +
	"\x05Spill\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.gramophile.GroupSpillR\x04type\x12\x1d\n" +
	"\n" +
	"look_ahead\x18\x02 \x01(\x05R\tlookAhead\"_\n" +
	"\rArtistMapping\x12#\n" +
	"\rleader_artist\x18\x01 \x01(\tR\fleaderArtist\x12)\n" +
	"\x10following_artist\x18\x02 \x03(\tR\x0ffollowingArtist\"y\n" +
	"\bGrouping\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.gramophile.GroupingTypeR\x04type\x12?\n" +
	"\x0eartist_weights\x18\x02 \x03(\v2\x18.gramophile.ArtistWeightR\rartistWeights\"@\n" +
	"\vLabelWeight\x12\x19\n" +
	"\blabel_id\x18\x01 \x01(\x05R\alabelId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\"C\n" +
	"\fArtistWeight\x12\x1b\n" +
	"\tartist_id\x18\x01 \x01(\x05R\bartistId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\"\x89\x01\n" +
	"\x05Space\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x05R\x05units\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x02R\x05width\x12*\n" +
	"\x06layout\x18\a \x01(\x0e2\x12.gramophile.LayoutR\x06layout\"s\n" +
	"\tFolderSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\x05R\x06folder\x12$\n" +
	"\x04sort\x18\x04 \x01(\x0e2\x10.gramophile.SortR\x04sort\"_\n" +
	"\x11ArtistTranslation\x12#\n" +
	"\rartist_prefix\x18\x01 \x01(\tR\fartistPrefix\x12%\n" +
	"\x0eordered_artist\x18\x02 \x01(\tR\rorderedArtist*K\n" +
	"\x14MissingWidthHandling\x12\x18\n" +
	"\x14MISSING_WIDTH_IGNORE\x10\x00\x12\x19\n" +
	"\x15MISSING_WIDTH_AVERAGE\x10\x01*h\n" +
	"\x04Sort\x12\x0f\n" +
	"\vARTIST_YEAR\x10\x00\x12\x0f\n" +
	"\vLABEL_CATNO\x10\x01\x12\x10\n" +
	"\fRELEASE_YEAR\x10\x02\x12\x19\n" +
	"\x15EARLIEST_RELEASE_YEAR\x10\x03\x12\x11\n" +
	"\rADDITION_DATE\x10\x04*\x1e\n" +
	"\x06Layout\x12\t\n" +
	"\x05TIGHT\x10\x00\x12\t\n" +
	"\x05LOOSE\x10\x01**\n" +
	"\aDensity\x12\t\n" +
	"\x05COUNT\x10\x00\x12\t\n" +
	"\x05DISKS\x10\x01\x12\t\n" +
	"\x05WIDTH\x10\x02*=\n" +
	"\x0fOrganisationUse\x12\x13\n" +
	"\x0fORG_USE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11ORG_USE_LISTENING\x10\x01*:\n" +
	"\n" +
	"GroupSpill\x12\x12\n" +
	"\x0eSPILL_NO_SPILL\x10\x00\x12\x18\n" +
	"\x14SPILL_BREAK_ORDERING\x10\x01*<\n" +
	"\fGroupingType\x12\x18\n" +
	"\x14GROUPING_NO_GROUPING\x10\x00\x12\x12\n" +
	"\x0eGROUPING_GROUP\x10\x01B*Z(github.com/brotherlogic/gramophile/protob\x06proto3"

var (
	file_organisation_proto_rawDescOnce sync.Once
	file_organisation_proto_rawDescData []byte
)

func file_organisation_proto_rawDescGZIP() []byte {
	file_organisation_proto_rawDescOnce.Do(func() {
		file_organisation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_organisation_proto_rawDesc), len(file_organisation_proto_rawDesc)))
	})
	return file_organisation_proto_rawDescData
}

var file_organisation_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_organisation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_organisation_proto_goTypes = []any{
	(MissingWidthHandling)(0),    // 0: gramophile.MissingWidthHandling
	(Sort)(0),                    // 1: gramophile.Sort
	(Layout)(0),                  // 2: gramophile.Layout
	(Density)(0),                 // 3: gramophile.Density
	(OrganisationUse)(0),         // 4: gramophile.OrganisationUse
	(GroupSpill)(0),              // 5: gramophile.GroupSpill
	(GroupingType)(0),            // 6: gramophile.GroupingType
	(*OrganisationConfig)(nil),   // 7: gramophile.OrganisationConfig
	(*OrganisationSnapshot)(nil), // 8: gramophile.OrganisationSnapshot
	(*SnapshotDiff)(nil),         // 9: gramophile.SnapshotDiff
	(*Move)(nil),                 // 10: gramophile.Move
	(*Placement)(nil),            // 11: gramophile.Placement
	(*Organisation)(nil),         // 12: gramophile.Organisation
	(*Spill)(nil),                // 13: gramophile.Spill
	(*ArtistMapping)(nil),        // 14: gramophile.ArtistMapping
	(*Grouping)(nil),             // 15: gramophile.Grouping
	(*LabelWeight)(nil),          // 16: gramophile.LabelWeight
	(*ArtistWeight)(nil),         // 17: gramophile.ArtistWeight
	(*Space)(nil),                // 18: gramophile.Space
	(*FolderSet)(nil),            // 19: gramophile.FolderSet
	(*ArtistTranslation)(nil),    // 20: gramophile.ArtistTranslation
}
var file_organisation_proto_depIdxs = []int32{
	20, // 0: gramophile.OrganisationConfig.artist_translation:type_name -> gramophile.ArtistTranslation
	12, // 1: gramophile.OrganisationConfig.organisations:type_name -> gramophile.Organisation
	16, // 2: gramophile.OrganisationConfig.label_ranking:type_name -> gramophile.LabelWeight
	11, // 3: gramophile.OrganisationSnapshot.placements:type_name -> gramophile.Placement
	10, // 4: gramophile.SnapshotDiff.moves:type_name -> gramophile.Move
	11, // 5: gramophile.Move.start:type_name -> gramophile.Placement
	11, // 6: gramophile.Move.end:type_name -> gramophile.Placement
	19, // 7: gramophile.Organisation.foldersets:type_name -> gramophile.FolderSet
	18, // 8: gramophile.Organisation.spaces:type_name -> gramophile.Space
	3,  // 9: gramophile.Organisation.density:type_name -> gramophile.Density
	0,  // 10: gramophile.Organisation.missing_width_handling:type_name -> gramophile.MissingWidthHandling
	15, // 11: gramophile.Organisation.grouping:type_name -> gramophile.Grouping
	13, // 12: gramophile.Organisation.spill:type_name -> gramophile.Spill
	4,  // 13: gramophile.Organisation.use:type_name -> gramophile.OrganisationUse
	5,  // 14: gramophile.Spill.type:type_name -> gramophile.GroupSpill
	6,  // 15: gramophile.Grouping.type:type_name -> gramophile.GroupingType
	17, // 16: gramophile.Grouping.artist_weights:type_name -> gramophile.ArtistWeight
	2,  // 17: gramophile.Space.layout:type_name -> gramophile.Layout
	1,  // 18: gramophile.FolderSet.sort:type_name -> gramophile.Sort
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_organisation_proto_init() }
func file_organisation_proto_init() {
	if File_organisation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organisation_proto_rawDesc), len(file_organisation_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organisation_proto_goTypes,
		DependencyIndexes: file_organisation_proto_depIdxs,
		EnumInfos:         file_organisation_proto_enumTypes,
		MessageInfos:      file_organisation_proto_msgTypes,
	}.Build()
	File_organisation_proto = out.File
	file_organisation_proto_goTypes = nil
	file_organisation_proto_depIdxs = nil
}
